config/routes.rb
App::Application.routes.draw do

  get "memberships/create"

  get "memberships/destroy"

  resources :users do
    member do
      get :following, :followers
      get :organizations
    end
  end
  
  resources :organizations do
    member do
      get :members
    end
  end
  
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :password_resets
  
  root to: 'static_pages#home'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  
  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                  :integer         not null, primary key
#  name                :string(255)
#  location            :string(255)
#  cost                :string(255)
#  start               :datetime
#  end                 :datetime
#  duration            :integer
#  created_at          :datetime        not null
#  updated_at          :datetime        not null
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  organization_id     :integer
#  in_short            :text
#  objective           :text
#  who_should_apply    :text
#  further_details     :text
#  mission_type        :string(255)
#  status              :string(255)
#  cap                 :integer
#  applicant_count     :integer
#

class Project < ActiveRecord::Base
  attr_accessible :name, :location, :cost, :start, :end, :duration, :avatar, :organization_id,
                  :in_short, :objective, :who_should_apply, :further_details, :mission_type, :status,
                  :cap, :applicant_count
  has_attached_file :avatar
  
  belongs_to :organization
  
  validates :name, presence: true, length: { maximum: 250 }
  validates :in_short, length: { maximum: 400 }
  validates :organization_id, presence: true
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :signed_in_organization,  
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :owning_organization,    only: [:edit, :update]
  
  def index
    @projects = Project.paginate(page: params[:page])
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_organization.projects.build(params[:project])
    if @project.save
      flash[:success] = "Great! A new project has been created."
      redirect_to @project
    else
      render 'new'
    end    
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:success] = "Information updated"
      redirect_to @project
    else
      render 'edit'
    end
  end

  

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project destroyed."
    redirect_to organization_path

  end

end
  

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def current_project=(project)
     @current_project = project
   end
   
   def project_owner
      @project.organization == current_organization
    end
    
    def owning_organization
      @organization = Project.find(params[:id]).organization
      @project = Project.find(params[:id])
      redirect_to root_path unless current_organization?(@organization)
    end
   
end

app/views/projects/_avatar.html.erb
<section>
	<% if @project.avatar_file_name.nil? %>	
		<%= link_to image_tag("default_avatar.png", size: '150x150'), edit_project_path %>
	<% else %>
		<%= image_tag @project.avatar, size: '150x150' %>
	<%end%>
</section>

app/views/projects/_delete_project.html.erb
<%= form_for(current_organization.projects.find_by_id(@project.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Delete", class: "btn btn-large btn-danger" %>
<% end %>

app/views/projects/_further_details.html.erb
<div class="well">
	<h3>Further Details</h3></br>
		<% if @project.further_details == nil || @project.further_details == ""%>
			<%= link_to "Add some contence", edit_project_path%>
		<% else %>
			<%= @project.further_details %>
		<%end%>
</div>

app/views/projects/_mission.html.erb
<h3>The Mission</h3></br>
<div class="well">
		<% if @project.in_short == nil || @project.in_short == ""%>
			<%= link_to "In short (What it's all about)", edit_project_path %>
		<% else %>
			<%= @project.in_short %>
		<%end%>
</div>

app/views/projects/_objective.html.erb
<div class="well">
	<h3>Objective</h3></br>
		<% if @project.objective == nil || @project.objective == ""%>
			<%= link_to "In short (What it's all about)", edit_project_path%>
		<% else %>
			<%= @project.objective %>
		<%end%>
</div>

app/views/projects/_project.html.erb
<li>
	<% if project.avatar_file_name.nil? %>
		<%= image_tag("default_avatar.png", :size => "64x64") %>
	<% else %>	  
		<%= image_tag(project.avatar, :size => "64x64") %>
	<% end %>
  <%= link_to project.name, project %>
</li>

app/views/projects/_status.html.erb
<a data-toggle="collapse" data-target="#demo">View Status</a>
<div class=" collapse in" id="demo">

	<% if @project.cap %>
		<% if @project.applicant_count == @project.cap || @project.applicant_count.nil? %>
			<h3 style='display: inline-block;'>Status <span class="label label-success"> OPEN</span></h3>
			<h3 style='display: inline-block;'>Cap <span class="label"><%= @project.cap %></span>  </h3>
		<%end%>
	<%else%>
	<div>
		<h3 style='display: inline-block;'>Status <span class="alert alert-error" style="font-size: 15px; padding: 0px"> CLOSED</span></h3>
		<h3 style='display: inline-block;'>Cap <span class="label"><%= @project.cap %>1</span>  </h3>
	<%end%>
	</br>
</div>
</br>

<div class=" well">
	<strong><%= @project.mission_type%></strong>
</div>

app/views/projects/_who_should_apply.html.erb
<div class="well">
	<h3>Who Should Apply</h3></br>
		<% if @project.who_should_apply == nil || @project.who_should_apply == ""%>
			<%= link_to "Who Should Apply", edit_project_path%>
		<% else %>
			<%= @project.who_should_apply %>
		<%end%>
</div>

app/views/projects/edit.html.erb
<% provide(:title, "Edit Project") %> 
<h1>Update Project</h1>
<div class="row">
  <div class="span6 offset3">
		
  
		<%= form_for @project, :html => { :multipart => true } do |f| %>
		
		    <%= render 'shared/error_messages', object: f.object %>

				<legend>Basic Info & Stats</legend>
				
		    <%= f.label 'Project Name' %>
		    <%= f.text_field :name %>
		
				<%= f.label 'Type of activity' %>				
		    <%= f.select :mission_type, options_for_select([["", ""], "Disaster Relief", "Environmental", "Educational", "Medical", "Social"])%>
		
				<%= f.label 'Location' %>
		    <%= f.text_field :location, :placeholder => "University of Michigan, 48105 area" %>
		
				<%= f.label 'Participation Cost (In none please type "FREE")' %>
		    <%= f.text_field :cost, :placeholder => "5.50 USD" %>
		
				<%= f.label 'Starting Date' %>
		    <%= f.text_field :start, :placeholder => "5.50 USD" %>
		
				<%= f.label 'Ending Date' %>
		    <%= f.text_field :end, :placeholder => "5.50 USD" %>
				
				<%= f.label 'Project Duration' %>
		    <%= f.text_field :duration, :placeholder => "5.50 USD" %>
				
				
		
				<%= f.label 'Project Cap' %>
		    <%= f.text_field :cap, :placeholder => "5.50 USD" %>

				<legend>Descriptions</legend>
				
				<%= f.label "In short (400 characters or less)" %>
				Characters left: <span id="char-count">400</span>
		    <%= f.text_area :in_short , :maxlength => 400, :rows => 8%>
		
				<%= f.label "Objective (1000 characters or less)" %>
				Characters left: <span id="char-count">400</span>
		    <%= f.text_area :objective, :maxlength => 400, :rows => 8 %>
		
				<%= f.label "Who should apply (1000 characters or less)" %>
				Characters left: <span id="char-count">400</span>
		    <%= f.text_area :who_should_apply, :maxlength => 400, :rows => 8 %>
		
				<%= f.label "Further details (1000 characters or less)" %>
				Characters left: <span id="char-count">400</span>
		    <%= f.text_area :further_details, :maxlength => 400, :rows => 8 %>
				<legend>Project Picture</legend>
				
				<div class="well form-inline"><p>Project Picture</p>
				<%= f.file_field :avatar %>
				</div>

				<div class="form-actions">
		      <%= f.submit "Save", class: "btn btn-large btn-primary" %>
					<%= link_to "Cancel", project_path, class: "btn btn-large"%>
				</div>
		<%end%>
  </div>
</div>					

<script type="text/javascript">	
var maxLen = 400;
$(function() { setCharCount($('#project_in_short'));	}); 
$('#project_in_short').live('keyup keydown', function(e) { setCharCount($(this));	});	 
function setCharCount(object) {	 var left = maxLen - object.val().length;	 $('#char-count').html(left);	}
</script>

app/views/projects/new.html.erb
<% provide(:title, "New Project") %> 
<h1>Create a Project</h1>

<div class="row">
  <div class="span6 offset3">
  
	<%= form_for @project, :html => { :multipart => true }  do |f| %>
	    <%= render 'shared/error_messages', object: f.object %>

	    <%= f.label 'Project Name' %>
	    <%= f.text_field :name %>

			<%= f.label "In short (400 characters or less)" %>
			Characters left: <span id="char-count">400</span>
	    <%= f.text_area :in_short, :maxlength => 400, :rows => 8 %>
	
			<div class="well form-inline"><p>Project Picture</p>
			<%= f.file_field :avatar %>
			</div>

			<div class="form-actions">
	      <%= f.submit "Save", class: "btn btn-large btn-primary" %>
				<%= link_to "Cancel", organizations_path, class: "btn btn-large"%>
			</div>

	  <% end %>

  </div>
</div>					

<script type="text/javascript">	
var maxLen = 400;
$(function() { setCharCount($('#project_in_short'));	}); 
$('#project_in_short').live('keyup keydown', function(e) { setCharCount($(this));	});	 
function setCharCount(object) {	 var left = maxLen - object.val().length;	 $('#char-count').html(left);	}
</script>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>
<div class="row">
	<aside class="span2">
		<%= render 'avatar'%>
		<%= render 'status'%>
	</aside>
	
	<div class="span9">
		<h1 id="modeltitle">	
			<%= @project.name %>
		</h1>

		<h3 style='display: inline-block;'> Project by <%= @project.organization.name%></h3>
		
		<div style='margin-top: 1em;'>
		<% if project_owner %>
			<%= render 'delete_project'%>
		<% end %>
		</div>

		
		<%= render 'mission'%>

		<h3>The Details</h3></br>
		<%= render 'objective'%>
		<%= render 'who_should_apply'%>
		<%= render 'further_details'%>
		
		<div class="alert alert-error" style="font-size: big; padding: 1em">ATTENTION: This project activates only if cap is met.</div>
		
		<label class="checkbox">
		    <input type="checkbox"> By applying to this project I agree to fully commit my time for the dates stated.
		</label>
		<div class="btn btn-large btn-primary offset3">Apply</div>
		</div>
		
		
	</div>
</div>