config/routes.rb
App::Application.routes.draw do

  get "memberships/create"

  get "memberships/destroy"

  resources :users do
    member do
      get :following, :followers
      get :organizations
    end
  end
  
  resources :organizations do
    member do
      get :members
    end
  end
  
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :password_resets
  
  root to: 'static_pages#home'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  
  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  password_digest        :string(255)
#  remember_token_org     :string(255)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  url                    :string(255)
#  mission                :text
#  description            :text
#  active_field_1         :string(255)
#  active_field_2         :string(255)
#  active_field_3         :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#

class Organization < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :mission, :description, :url, 
                  :facebook_link, :twitter_link, :avatar, :active_field_1, :active_field_2, :active_field_3
  has_attached_file :avatar
  has_secure_password
  
  has_many :reverse_memberships, class_name:  "Membership",   #need to include class name, or otherwise will search for reverse_memberships class, which doesnt exist
                                 dependent:  :destroy           #, foreign_key: "organization_id"      not needed here since it's inferred from the name
  has_many :users, through: :reverse_memberships
  has_many :projects, dependent: :destroy

  before_save { |organization| organization.email = organization.email.downcase }
  before_save { generate_token(:remember_token_org) }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :mission, length: { maximum: 360 }
  validates :description, length: { maximum: 2000 }
   
  def feed
    Micropost.from_organizations_followed_by(self)
  end
  
  def following?(other_organization)
    relationships.find_by_followed_id(other_organization.id)
  end
  
  def follow!(other_organization)
    relationships.create!(followed_id: other_organization.id)
  end
  
  def unfollow!(other_organization)
    relationships.find_by_followed_id(other_organization.id).destroy
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(:validate => false)
    OrganizationMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Organization.exists?(column => self[column])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  
    before_filter :signed_in_organization,  
                  only: [:index, :edit, :update, :destroy, :following, :followers]
    before_filter :correct_organization,    only: [:edit, :update]

    def index
      @users = User.paginate(page: params[:page])
      @organizations = Organization.paginate(page: params[:page])
      @projects = Project.paginate(page: params[:page])
    end

    def show
      @organization = Organization.find(params[:id])
    end

    def new
      @organization = Organization.new
    end

    def create
      @organization = Organization.new(params[:organization])
      if @organization.save
        #OrganizationMailer.signup_confirmation(@organization).deliver
        sign_in_org @organization
        flash[:success] = "Welcome! You have Signed up successfully."
        redirect_to @organization
        #redirect_to @organization, notice: "Welcome! You have Signed up successfully."

      else
        render 'new'
      end    
    end

    def edit
    end

    def update
      if @organization.update_attributes(params[:organization])
        flash[:success] = "Profile updated"
        sign_in_org @organization
        redirect_to @organization
      else
        render 'edit'
      end
    end

    def destroy
      Organization.find(params[:id]).destroy
      flash[:success] = "Organization destroyed."
      redirect_to organizations_path
    end

    def following
      @title = "Following"
      @organization = Organization.find(params[:id])
      @organizations = @organization.followed_organizations.paginate(page: params[:page])
      render 'show_follow'
    end

    def followers
      @title = "Followers"
      @organization = Organization.find(params[:id])
      @organizations = @organization.followers.paginate(page: params[:page])
      render 'show_follow'
    end
    
    private

      def correct_organization
        @organization = Organization.find(params[:id])
        redirect_to root_path unless current_organization?(@organization)
      end

    

  end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  
  def sign_in_org(organization)
    if params[:remember_me]
      cookies.permanent[:remember_token_org] = organization.remember_token
    else
      cookies[:remember_token_org] = organization.remember_token_org
    end
    self.current_organization = organization
  end
  
  def signed_in_organization?
    !current_organization.nil?
  end
  
  def current_organization=(organization)
    @current_organization = organization
  end

  def current_organization
    @current_organization ||= Organization.find_by_remember_token_org!(cookies[:remember_token_org]) if cookies[:remember_token_org]
  end
  
  
  def current_organization?(organization)
    organization == current_organization
  end
  
  def signed_in_organization
    unless signed_in_organization?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
  
end

app/views/organizations/_avatar.html.erb
<section>
	<% if @organization.avatar_file_name.nil? %>	
		<%= link_to image_tag("default_avatar.png", size: '150x150'), edit_organization_path %>
	<% else %>
		<%= image_tag @organization.avatar, size: '150x150' %>
	<%end%>
</section>

app/views/organizations/_basic_info.html.erb
<%= form_for @organization, :html => { :multipart => true }  do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

		<div class="well">
		<%= f.label 'Active Fields (Choose up to 3)' %>
    <%= f.text_field :active_field_1, :placeholder => "Disaster Relief" %>
		<%= f.text_field :active_field_2, :placeholder => "Environmental" %>
		<%= f.text_field :active_field_3, :placeholder => "Education" %>
		</div>

		<%= f.label "Your Mission (400 characters or less)" %>
    Characters left: <span id="char-count">400</span>
    <%= f.text_area :mission , :maxlength => 400, :rows => 8%>

		<%= f.label "Detailed Description (2000 characters or less)" %>
		Characters left: <span id="char-count">2000</span>
    <%= f.text_area :description, :maxlength => 2000, :rows => 8 %>

		<%= f.label 'Website' %>
    <%= f.text_field :url, :placeholder => "www.activehelper.org" %>

		<%= f.label "Facebook URL" %>
    <%= f.text_field :facebook_link, :placeholder => "www.facebook.com/active.helper" %>

		<%= f.label "Twitter URL" %>
    <%= f.text_field :twitter_link, :placeholder => "www.twitter.com/active_helper" %>

		<div class="well form-inline"><p>Change Profile Picture</p>
		<%= f.file_field :avatar %>
		</div>

		<%= f.hidden_field :password, value: @organization.password_digest %>
    <%= f.hidden_field :password_confirmation, value: @organization.password_digest %>

		<div class="form-actions">
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<%= link_to "Cancel", user_path, class: "btn btn-large"%>
		</div>
		
  <% end %>


	<script type="text/javascript">	
	var maxLen = 400;
	$(function() { setCharCount($('#organization_mission'));	});
	$('#organization_mission').live('keyup keydown', function(e) { setCharCount($(this));	});	 
	function setCharCount(object) {	 var left = maxLen - object.val().length;	 $('#char-count').html(left);	}
	</script>

app/views/organizations/_description.html.erb
<div class="well">
<% if current_organization?(@organization) %>
		<% if @organization.description == nil || @organization.description == ""%>
			<%= link_to "About your Organization", edit_organization_path(current_organization) %>
		<% else %>
			<%= @organization.description %>
		<%end%>
	<% else %>
		<% if @organization.description == nil || @organization.description == ""%>
			<i>No description available<i>
 		<% else %>
			<%= @organization.description %>
		<%end%>
	<%end%>
</div>

app/views/organizations/_join.html.erb
<%= form_for(current_user.memberships.build(organization_id: @organization.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :organization_id %></div>
  <%= f.submit "Join", class: "btn btn-large btn-primary" %>
<% end %>

app/views/organizations/_join_form.html.erb
<% if current_user %>
	<div id="join_form">
	   	<% if current_user.member?(@organization) %>
	     <%= render 'leave' %>
	   <% else %>
	     <%= render 'join' %>
	   <% end %>
	</div>
<%end%>

app/views/organizations/_leave.html.erb
<%= form_for(current_user.memberships.find_by_organization_id(@organization),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Leave", class: "btn btn-large" %>
<% end %>

app/views/organizations/_mission.html.erb
<div class="well">
<% if current_organization?(@organization) %>
		<% if @organization.mission == nil || @organization.mission == ""%>
			<%= link_to "Mission of Organization", edit_organization_path(current_organization) %>
		<% else %>
			<%= @organization.mission %>
		<%end%>
	<% else %>
		<% if @organization.mission == nil || @organization.mission == ""%>
			<i>No description available<i>
 		<% else %>
			<%= @organization.mission %>
		<%end%>
	<%end%>
</div>

app/views/organizations/_organization.html.erb
<li>
	<% if organization.avatar_file_name.nil? %>
		<%= image_tag("default_avatar.png", :size => "64x64") %>
	<% else %>	  
		<%= image_tag(organization.avatar, :size => "64x64") %>
	<% end %>
  <%= link_to organization.name, organization %>
</li>
<!--

	<%# if current_user.admin? && !current_user?(user) %>
	| <%#= link_to "delete", organization, method: :delete,
																data: { confirm: "You sure?" } %>
 	<%# end %>
</li>

-->

app/views/organizations/_profile_info.html.erb
<h1 id="modeltitle" style:"display: block;">	
	<%= @organization.name %>
</h1>

<span class="offset0">
<% if !@organization.facebook_link.blank? %>
	<%= link_to image_tag("f_logo.png", size: "40x40"),  "http://" + @organization.facebook_link, :target => '_blank' %>
<% end %>

<% if !@organization.twitter_link.blank? %>
	<%= link_to image_tag("t_logo.png", size: "40x40"), "http://" + @organization.twitter_link, :target => '_blank' %>
<% end %>
</span>

app/views/organizations/_security.html.erb
<%= form_for @organization, :html => { :multipart => true } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

		<%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.text_field :password_confirmation %>
	
		<div class="form-actions">
			<%= f.submit "Change my password", class: "btn btn-large btn-primary" %>
			<%= link_to "Cancel", organization_path, class: "btn btn-large"%>
		</div>
<% end %>

app/views/organizations/_stats.html.erb
<div id="members">
	<h4>Stats</h4>
	<div class="well" id="members">
	
	<%= @organization.users.count%> <% if @organization.users.count == 1%> Member <%else%> Members <%end%></br>	
	<%= @organization.projects.count%> Active	<% if @organization.projects.count == 1%> Project <%else%> Projects <%end%></br>
	</div>
</div>	

app/views/organizations/edit.html.erb
<% provide(:title, "Edit organization") %> 
<h1>Update your profile</h1>

<div class="tabbable tabs-left offset1">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Basic Info</a></li>
		<li><a href="#tab2" data-toggle="tab">Security</a></li>
  </ul>
	<div class="tab-content">
  	<div class="tab-pane active" id="tab1">
			<div class="row">
			  <div class="span6 offset1">
				
				<legend>Basic Info</legend>
			  <%= render 'basic_info' %>

			  </div>
			</div>					
    </div>
    <div class="tab-pane" id="tab2">
      <div class="row">
			  <div class="span6 offset1">
				
				<legend>Change Password</legend>
				<%= render 'security' %>
				
				</div>
    	</div>
  	</div>
	</div>
</div>

app/views/organizations/new.html.erb
<% provide(:title, 'Sign Up Organization') %>
<h1>Sign up for Organizations</h1>

<div class="row">
  <div class="span4 offset4">
    <%= form_for(@organization) do |f| %>
			<%=render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<% provide(:title, @organization.name) %>
<div class="row">
	<aside class="span2">
		<%= render 'avatar'%>
		<%= render 'join_form'%>
		<%= render 'stats' %>
		<%= render 'active_fields' %>
	</aside>
	
	<div class="span10">
		<%= render 'profile_info'%>
		
		
		<% if !@organization.url.blank? %>
		<p><h3>Homepage: <%= link_to @organization.url, "http://" + @organization.url, :target => '_blank' %></h3></p>
		<% end %>
		
		<% if current_organization?(@organization)%>
			<span class="btn btn-link" style="margin-bottom: 8px;"><%= link_to "Create Project", new_project_path %></span>
		<% end %>
		
		<%= render 'mission' %>
		<%= render 'description' %>
		
	
	  </div>
	</div>
</div>