config/routes.rb
App::Application.routes.draw do

  get "memberships/create"

  get "memberships/destroy"

  resources :users do
    member do
      get :following, :followers
      get :organizations
    end
  end
  
  resources :organizations do
    member do
      get :members
    end
  end
  
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :memberships, only: [:create, :destroy]
  resources :password_resets
  
  root to: 'static_pages#home'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  
  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post

end

app/views/layouts/_default_header.html.erb
<div style=" margin-top: 5px; margin-bottom: -20px;">
	<%= form_tag sessions_path do %>
	    <div style='display: inline-block;'><%= text_field_tag :email, params[:email], :placeholder => "Email" %></div>
	    <div style='display: inline-block;'><%= password_field_tag :password, params[:password], :placeholder => "Password" %></div>

				<%= check_box_tag :remember_me, 1, params[:remember_me] %>
				Remember me
			
			<div class="actions" style='display: inline-block; padding-bottom: 5px; margin-top: -10px;'><%= submit_tag "Sign in" , class: "btn btn-info" %></div>
		<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container" style="margin:0 auto;">
		<div class="row">		

			<nav style="text-align: center;">
				<ul style="display: inline-block;">
					<li><%= link_to "About", about_path %> |</li>
					<li><%= link_to "How It Works", about_path %> |</li>
					<li><%= link_to "Support Us", about_path %> |</li>
					<li><%= link_to "Jobs", about_path %> |</li>
					<li><a href="https://gothic1234.herokuapp.com">News</a> |</li>
					<li><%= link_to "Contact Us", messages_path %></li>
				</ul>
			</nav>
			<div id="Copyright">Copyright &copy 2012 Vena Biometrics. All rights reserved.</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-static-top">
	<div class="navbar-inner">
		<div class="container">
				<%= link_to "Active Helper", root_path, id: "logo" %>
	       	<ul class="nav pull-right">
						<% if current_user %>
						
							<%= render 'layouts/user_header'%>
							
						<% elsif current_organization %>
						
							<%= render 'layouts/org_header'%>
							
	          <% else %>
	
							<%= render 'layouts/default_header'%>
							
	          <% end %>
	        </ul>
			</div>
		</div>
</div>

app/views/layouts/_org_header.html.erb
<form class="navbar-search" >
  <input type="text" class="search-query" style="background: white;" placeholder="Profiles/Orgs">
</form>
<li><%= link_to "Home", current_organization %></li>
<li><%= link_to "Profile", current_organization %></li>
<li><%= link_to "Browse", organizations_path %></li>
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Account <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Settings", edit_organization_path(current_organization) %></li>
    <li class="divider"></li>
    <li>
      <%= link_to "Sign Out", signout_path, method: "delete" %>
    </li>
  </ul>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user_header.html.erb
<form class="navbar-search" >
  <input type="text" class="search-query" style="background: white;" placeholder="Profiles/Orgs">
</form>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Profile", current_user %></li>
<li><%= link_to "Browse", users_path %></li>
<li id="fat-menu" class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Account <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li class="divider"></li>
    <li>
      <%= link_to "Sign Out", signout_path, method: "delete" %>
    </li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title))%></title>
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
</head>

<body>
	<div class="wrapper">
		<%= render 'layouts/header'%>
		<div class="container" style="padding-top: 20px;">
			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>

			<%= yield %>
		</div>
		<div class="push"></div>
	</div><!-- wrapper finish -->

	<%= render 'layouts/footer' %>
</body>
</html>